[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
matrix-sdk = { version = "0.7", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"

chat_core = { path = "../chat_core" }

