[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.9"
tokio = { version = "1", features = ["full"] }
network = { path = "../network" }
chat_core = { path = "../chat_core" }


[build-dependencies]
slint-build = "1.9"



